### PR TITLE
GUI Tweaks and an Issue Fix

### LINKED ISSUE #101: Missile heading upside while falling
https://i.imgur.com/IGjVhMP.png
Occured when I launched small missile with TNT warhead. Launched from portable launcher.

VoltzEngine-1.7.10-0.4.0b263-dev
ICBM-1.7.10-2.4.0b253-dev

### PR DESCRIPTION
**Pull request by Mirosta**
Fixed #101
Tweaked GUIs on Launch Controller and Missile Workstation

### CODE REVIEW

**Comment by Mirosta** [comment]
GUI changes can be seen here http://imgur.com/a/lmJqH

**Comment by Kolatra** [comment]
Looks pretty. I like it.

**Comment by DarkGuardsman** [comment]
Before I pull we have a new policy that contributors need to agree to the CLA https://docs.google.com/document/d/105N6q63OJnzrWjMbydFYFUlHmK6spc8P8da8qkduFRs/edit?usp=sharing

**Comment by Mirosta** [comment]
Yeah I read it through before starting work. I agree to it but do you want something more formal?

**Comment by Mirosta** [comment]
Also do you have anywhere you discuss the project, other than GitHub, that I should be aware of?

**Comment by DarkGuardsman** [comment]
Esper net irc #BuiltBroken #BuiltBrokenModding #ICBM

**Pull request merged**
